# Generated by Django 4.1.7 on 2023-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.IntegerField(null=True),
        ),
    ]
